import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
 en:{
   home:"Home",
   diary:"Diary",
   daily:"Daily",
   travel:"Travel",
   add:"Add",
   update:"Update",
   save:"Save",
   delete:"Delete",
   privacy:"Privacy",
   name:"Name",
   description:"Description",
   culture:"Culture",
   guest:"Guest",
   place:"Place",
   notPlace:"The locale has not been placed",
   date:"Date",
   photos:"Photos",
   experiences:"Experiences",
   friends:"Friends",
   profile:"Profile",
   map:"Map",
   search:"Search",
   searchBy: "Search by",
   notifications:"Notifications",
   signup:"Don't have an account? Sign up",
   loging:"Log in",
   report:"Report",
   cancel:"Cancel",
   follow:"Follow",
   unfollow:"Unfollow",
   following: "Following",
   followers:"Followers",
   username:"Username",
   password:"Password",
   termsConditions:"Terms and Conditions",
   accept:"accept",
   email:"Email Address",
   wrongPassEmail: "Wrong password or email",
   changePassword: " Change password",
   privateInformation: "Private Information",
   changePerfilPhoto: "Change profile photo",
   select: "Select",
   takePhoto: "Take Photo",
   chooseFromLibrary: "From Library",
   nicknameExits: "Nickname already exists ",
   tips:"Tips",
   country: "Country",
   lastName: "Last name",
   nickname: "Nickname",
   blankinputs: "Some inputs are blanks",
   blankName: "Name can not be empty",
   birthday: "Birthday",
   passwordWeak : "The password is too weak",
   emailExits: "Email already exists",
   espaces: "Espaces",
   restart: "Restart session to change email",
   touchToRestart: "Touch this message if you wish to log out",
   createDiary:"Create diary",
   editDiary:"Edit diary",
   gallery: "Gallery",
   me:"Me",
   myDiaries:"Diaries",
   loading: "Loading...",
   forgetpass: "Forgot password?",
   createNewAccount: "Create new account",
   seeMore: "See more",
   checkEmail: "Check your e-mail",
   unknowEmail: "The email does not exists",
   somethingGoesWrong: "Something goes wrong",
   nowYouFollow: "Now you follow ",
   nowYouUnfollow: "Now you unfollow ",
   publicInformation: "Public information",
   signOff: "Sign off",
   you: "You",
   iAppearWhen: "I appear when you don't have diaries",
   touchMeToCreate: "Touch me to create one",
   map: "Map",
   confirmPopUp: "¿Do you wish to delete?",
   yes: "Yes",
   no: "No",
   confirm: "Confirm",
   howDeleteImage: "Press and hold image to delete",
   imageDeleted: "Image deleted",
   notifications: "Notifications",
   noInternet: "Internet connection not found",
   iAppearWhenHome: "I appear when you don't follow no one",
   touchMeToCreateHome: "Touch me to follow new friends",
   iAppearWhenAddPlaceInDaily: "I appear when you don't have dailies",
   restaurant: "restaurants",
   establishment: "establishments",
   coffe: "coffee shops",
   food: "food",
   bar: "pubs",
   theUser: "The user",
   sendInvitation: "has sent you an invitation to participate in the diary",
   touchAccept: "touch to accept the invitation",
   acceptAlreadyInvitation: "You've already accepted the invitation to diary",
   hasFollowed: "has followed you",
   acceptInvitation: "Accept the invitation to diary",
   changePhoto: "Change photo ",
   eject: "Eject",
   invite: "Invite",
   friendsSuggest: "Suggest friends",
   addThisPlaceToADaily: "Add this place a to daily",
   visitTheDailies: "Visit the dailies here!",
   wantLogout: 'Do you want to log out?',
   thisUserHasNoDiaries: "This user has no diaries",
   nothingToSeeHere: "Nothing to see here",
 },
 es:{
   home:"Inicio",
   diary:"Diario",
   daily:"Vivencia diaria",
   travel:"Viaje",
   add:"Agregar",
   update:"Actualizar",
   save:"Guardar",
   delete:"Eliminar",
   privacy:"Privacidad",
   name:"Nombre",
   description:"Descripción",
   culture:"Cultura",
   guest:"Invitado",
   place:"Lugar",
   notPlace:"La ubicación no ha sido colocada",
   date:"Fecha",
   photos:"Fotos",
   experiences:"Experiencias",
   friends:"Amigos",
   profile:"Perfil",
   map:"Mapa",
   search:"Buscar",
   searchBy:"Buscar por",
   notifications:"Notificaciones",
   signup:"¿No tienes una cuenta? Regístrate",
   loging:"Iniciar sesión",
   report:"Reportar",
   cancel:"Cancelar",
   follow:"Seguir",
   unfollow:"Dejar de seguir",
   following: "Seguidos",
   followers:"Seguidores",
   username:"Usuario",
   password:"Contraseña",
   termsConditions:"Terminos y condiciones",
   accept:"Aceptar",
   email:"Correo electrónico",
   wrongPassEmail: "Contraseña o correo electrónico incorrectos",
   changePassword: "Cambiar contraseña",
   privateInformation: "Información Privada",
   changePerfilPhoto: "Cambiar foto de perfil",
   select: "Seleccionar",
   takePhoto: "Tomar Foto",
   chooseFromLibrary: "Desde Librería",
   nicknameExits: "Apodo ya existe ",
   tips:"Recomendaciones",
   country: "País",
   lastName: "Apellido",
   nickname: "Apodo",
   blankinputs: "Algunos campos están vacíos",
   blankName: "El nombre no puede ir vacío",
   birthday:"Cumpleaños",
   passwordWeak : "La contraseña es muy corta",
   emailExits: "Este correo electrónico ya existe",
   espaces: "Campos",
   restart: "Reinicia sesión para cambiar el correo",
   touchToRestart: "Toque este mensaje si desea cerrar sesión",
   createDiary:"Crear diario",
   editDiary:"Modificar diario",
   gallery: "Galería",
   me:"Yo",
   myDiaries:"Diarios",
   loading: "Cargando...",
   forgetpass: "¿Has olvidado la contraseña?",
   createNewAccount: "Crear nueva cuenta",
   seeMore: "Ver mas",
   checkEmail: "Revisar su correo electrónico",
   unknowEmail: "Correo electrónico no existe",
   somethingGoesWrong: "Algo malo sucedio ",
   nowYouFollow: "Ahora sigues a ",
   nowYouUnfollow: "Dejaste de seguir a ",
   publicInformation: "Información pública",
   signOff: "Cerrar sesión",
   you: "Tú",
   iAppearWhen: "Yo aparezco cuando no tienes diarios",
   touchMeToCreate: "Tocame para crear uno",
   map: "Mapa",
   confirmPopUp: "¿Deseas eliminar?",
   yes: "Sí",
   no: "No",
   confirm: "Confirmación",
   notifications: "Notificaciones",
   noInternet: "Conexión a internet no encontrada",
   iAppearWhenHome: "Yo aparezco cuando no sigues a nadie",
   touchMeToCreateHome: "Tocame para buscar y seguir amigos",
   howDeleteImage: "Mantenga presionado una imagen para eliminar",
   imageDeleted: "Imagen borrada",
   restaurant: "restaurantes",
   establishment: "establecimientos",
   coffe: "cafeterías",
   food: "comida",
   bar: "bares",
   theUser: "El usuario",
   sendInvitation: "te ha enviado una invitación para participar en el diario",
   touchAccept: "toca para aceptar la invitación ",
   acceptAlreadyInvitation: "Ya has aceptado la invitación al diario",
   hasFollowed: "te ha seguido",
   acceptInvitation: "¿Aceptar la invitación al diario",
  changePhoto: "Cambiar foto ",
  eject: "Expulsar",
  invite: "Invitar",
  friendsSuggest: "Sugerir amigos",
  addThisPlaceToADaily: "Agregar este lugar a la vivencia",
  visitTheDailies: "Visita las vivencias aquí!",
   wantLogout: '¿Deseas cerrar sesión?',
  thisUserHasNoDiaries: "Este usuario no tiene diarios",
  nothingToSeeHere: "Nada que ver aquí",
 },
 zh:{
   home:"首頁",
   diary:"日記",
   daily:"日常",
   travel:"旅行",
   add:"增",
   update:"更新",
   save:"儲存",
   delete:"刪除",
   privacy:"隱私",
   name:"名稱",
   description:"說明",
   culture:"文化",
   guest:"來賓",
   place:"地點",
   notPlace: "還沒選地點",
   date:"日期",
   photos:"相片",
   experiences:"經驗",
   friends:"朋友",
   profile:"個人檔案",
   map:"地圖",
   search:"搜尋",
   searchBy: "搜尋",
   notifications:"通知",
   signup:"¿您還沒有賬戶? 申請一個吧",
   loging:"登錄",
   report:"投訴",
   cancel:"取消",
   follow:"追蹤",
   unfollow:"取消追蹤",
   following: "追蹤",
   followers:"粉絲",
   username:"用戶名",
   password:"密碼",
   termsConditions:"條款和條件",
   accept:"接受",
   email:"電子郵件",
   wrongPassEmail: "電子郵件或密碼不正確",
   changePassword: "更改密碼",
   privateInformation: "私人信息",
   changePerfilPhoto: "更改個人照片",
   select: "選擇",
   takePhoto: "拍照",
   chooseFromLibrary: "從相簿挑選",
   nicknameExits: "用戶名已存在",
   tips:"建議",
   country: "國家",
   lastName: "姓",
   nickname: "暱稱",
   blankinputs: "有些空格是空的",
   blankName: "名稱不能是空的",
   birthday:"生日",
   passwordWeak : "密碼太短",
   emailExits: "電子郵件已存在",
   espaces: "空格",
   restart: "重新登錄才能更改郵件",
   touchToRestart: "登出請點這裡",
   createDiary:"新增日記",
   editDiary:"編輯日記",
   gallery: "相簿",
   me:"我",
   myDiaries:"我的日記",
   loading: "載入中...",
   forgetpass: "¿忘了密碼?",
   createNewAccount: "新增帳號",
   seeMore: "更多",
   checkEmail: "查看電子郵件",
   unknowEmail: "電子郵件不存在",
   somethingGoesWrong: "有發生異常 ",
   nowYouFollow: "您正在追蹤",
   nowYouUnfollow: "您取消追蹤",
   publicInformation: "公共信息",
   signOff: "登出",
   you: "您",
   iAppearWhen: "沒日記我就會出現",
   touchMeToCreate: "點我新增一個",
   map: "地圖",
   confirmPopUp: "¿確定要刪除嗎?",
   yes: "是",
   no: "否",
   confirm: "確認",
   howDeleteImage: "要刪除請按住圖片",
   imageDeleted: "圖片以刪除",
   restaurant: "restaurantes",
   establishment: "establecimientos",
   coffe: "cafeterías",
   food: "comida",
   bar: "bares",
 }
});



module.exports = strings;
