import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
 en:{
   home:"Home",
   diary:"Diary",
   daily:"Daily",
   travel:"Travel",
   add:"Add",
   update:"Update",
   save:"Save",
   delete:"Delete",
   privacy:"Privacy",
   name:"Name",
   description:"Description",
   culture:"Culture",
   guest:"Guest",
   place:"Place",
   date:"Date",
   photos:"Photos",
   experences:"Experences",
   friends:"Friends",
   profile:"Profile",
   map:"Map",
   search:"Search",
   notifications:"Notifications",
   singin:"Singin",
   singup:"Singup",
   loging:"Login",
   report:"Report",
   cancel:"Cancel",
   follow:"Follow",
   unfollow:"Unfollow",
   followers:"Followers",
   username:"Username",
   password:"Password",
   termsConditions:"Terms and Conditions",
   accept:"accept",
   email:"Email Address"
 },
 es:{
   home:"Inicio",
   diary:"Diario",
   daily:"Vivencia diaria",
   travel:"Viaje",
   add:"Agregar",
   update:"Atualizar",
   save:"Guardar",
   delete:"Eliminar",
   privacy:"Privacidad",
   name:"Nombre",
   description:"Descripción",
   culture:"Cultura",
   guest:"Invitado",
   place:"Lugar",
   date:"Fecha",
   photos:"Fotos",
   experences:"Experiencias",
   friends:"Amigos",
   profile:"Perfil",
   map:"Mapa",
   search:"Buscar",
   notifications:"Notificaciones",
   singup:"Registrarse",
   loging:"Iniciar sesión",
   report:"Reportar",
   cancel:"Cancelar",
   follow:"Seguir",
   unfollow:"Dejar de seguir",
   followers:"Seguidores",
   username:"Usuario",
   password:"Contraseña",
   termsConditions:"Terminos y condiciones",
   accept:"Aceptar",
   email:"Correo Electrónico"
 }
});



module.exports = strings;
