import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
 en:{
   home:"Home",
   diary:"Diary",
   daily:"Daily",
   travel:"Travel",
   add:"Add",
   update:"Update",
   save:"Save",
   delete:"Delete",
   privacy:"Privacy",
   name:"Name",
   description:"Description",
   culture:"Culture",
   guest:"Guest",
   place:"Place",
   date:"Date",
   photos:"Photos",
   experiences:"Experiences",
   friends:"Friends",
   profile:"Profile",
   map:"Map",
   search:"Search",
   notifications:"Notifications",
   singin:"Singin",
   signup:"Signup",
   loging:"Login",
   report:"Report",
   cancel:"Cancel",
   follow:"Follow",
   unfollow:"Unfollow",
   followers:"Followers",
   username:"Username",
   password:"Password",
   termsConditions:"Terms and Conditions",
   accept:"accept",
   email:"Email Address",
   wrongPassEmail: "Wrong password or email",
   changePassword: " Change password",
   privateInformation: "Private Information",
   changePerfilPhoto: "Change profile photo",
   select: "Select",
   takePhoto: "Take Photo",
   chooseFromLibrary: "From Library",
   nicknameExits: "Nickname already exists ",
   tips:"Tips",
   country: "Country",
   lastName: "Last name",
   nickname: "Nickname",
   blankinputs: "Some inputs are blanks",
   birthday: "Cumpleaños"

 },
 es:{
   home:"Inicio",
   diary:"Diario",
   daily:"Vivencia diaria",
   travel:"Viaje",
   add:"Agregar",
   update:"Atualizar",
   save:"Guardar",
   delete:"Eliminar",
   privacy:"Privacidad",
   name:"Nombre",
   description:"Descripción",
   culture:"Cultura",
   guest:"Invitado",
   place:"Lugar",
   date:"Fecha",
   photos:"Fotos",
   experiences:"Experiencias",
   friends:"Amigos",
   profile:"Perfil",
   map:"Mapa",
   search:"Buscar",
   notifications:"Notificaciones",
   signup:"Registrarse",
   loging:"Iniciar sesión",
   report:"Reportar",
   cancel:"Cancelar",
   follow:"Seguir",
   unfollow:"Dejar de seguir",
   followers:"Seguidores",
   username:"Usuario",
   password:"Contraseña",
   termsConditions:"Terminos y condiciones",
   accept:"Aceptar",
   email:"Correo Electrónico",
   wrongPassEmail: "Contraseña o correo electrónico incorrectos",
   changePassword: "Cambiar contraseña",
   privateInformation: "Información Privada",
   changePerfilPhoto: "Cambiar foto de perfil",
   select: "Seleccionar",
   takePhoto: "Tomar Foto",
   chooseFromLibrary: "Desde Librería",
   nicknameExits: "Apodo ya existe ",
   tips:"Recomendaciones",
   country: "Pais",
   lastName: "Apellido",
   nickname: "Apodo",
   blankinputs: "Algunas entradas estan vacias",
   birthday:"Cumpleaños"
 }
});



module.exports = strings;
